---
groups:
  - name: "all"
    jobs:
      - "publish-docroot"
      - "default-image"

jobs:
  - name: "default-image"
    serial: true
    plan:
      - get: "repository"
        resource: "repository.ci.docker"
        trigger: true
      - put: "default-docker-image"
        params:
          build: "repository/ci/docker/default"
        get_params:
          skip_download: true
  - name: "publish-docroot"
    plan:
      - get: "repository"
        trigger: true
      - get: "default-docker-image"
        trigger: true
        params:
          skip_download: true
      - task: "build"
        file: "repository/ci/tasks/build-docroot/config.yml"
        config:
          params:
            SITE_ENVIRONMENT: {{site_environment}}
            SITE_URL: {{site_url}}
      - put: "docroot-tgz"
        params:
          from: "docroot/(.*).tgz"
          to: "docroot/"

resources:
  - name: "repository"
    type: "git"
    source:
      uri: {{repository_uri}}
      branch: {{repository_branch}}
      private_key: {{repository_key}}
  - name: "repository.ci.docker"
    type: "git"
    source:
      uri: {{repository_uri}}
      branch: {{repository_branch}}
      private_key: {{repository_key}}
      paths:
        - "ci/docker/*"
  - name: "docroot-tgz"
    type: "s3"
    source:
      access_key_id: {{s3_access_key_id}}
      secret_access_key: {{s3_secret_access_key}}
      bucket: {{s3_bucket}}
      regexp: "docroot/(.+)-(?P<version>.+).tgz"
  - name: "default-docker-image"
    type: "docker-image"
    source:
      repository: {{docker_repository_default}}
      username: {{docker_username}}
      password: {{docker_password}}
      email: {{docker_email}}
