[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENABLEGITINFO = "true"
