type: dynamic-metalink
source:
  version_check: |
    git ls-remote --tags https://github.com/git/git.git \
      | cut -f2 \
      | grep -v '\^{}' \
      | grep -E '^refs/tags/v.+$' \
      | sed -E 's/^refs\/tags\/v(.+)$/\1/' \
      | grep -v '-' \
      | grep -E '^\d+\.\d+(\.\d+)?$'
  metalink_get: |
    jq -n '
      env.version | {
        "files": [
          { "name": "git-\(.).tar.gz",
            "urls": [ { "url": "https://mirrors.edge.kernel.org/pub/software/scm/git/git-\(.).tar.gz" } ] } ] }'
