type: dynamic-metalink
source:
  version_check: |
    git ls-remote --tags https://github.com/nginx/nginx.git \
      | cut -f2 \
      | grep -v '\^{}' \
      | grep -E '^refs/tags/release-.+$' \
      | sed -E 's/^refs\/tags\/release-(.+)$/\1/'
  metalink_get: |
    jq -n '
      "nginx-\(env.version).tar.gz" | {
        "files": [
          { "name": .,
            "urls": [ { "url": "https://nginx.org/download/\(.)" } ] } ] }'
