---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-main-bosh-docker
    tag: light
inputs:
- name: repo
- name: stemcell
  optional: true
run:
  path: repo/ci/tasks/test-deploy/run.sh
